version: '3.8'

services:

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: dictation_frontend
    
    ports:
      - "127.0.0.1:8088:80" 
    
    restart: always
    
  # ----------------------------------------
  # SERVICE 2: Backend (API de reconnaissance vocale)
  # ----------------------------------------
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: dictation_backend
    env_file:
      - ./backend/.env
    
    ports:
      - "127.0.0.1:3000:3000"
      
    restart: always